"""All prompt text lives here. This is the file you iterate on during Phase 1."""

from app.content.topics import render_hook_type_block


# Bump this every time you ship a meaningful change to SYSTEM_PROMPT or
# IMAGE_STYLE_PREFIX. New cards generated by this code path are stamped with
# this version; older cards retain whatever version they were minted under,
# so you can A/B compare prompt iterations in the feed/workbench.
CARD_VERSION = "v1"


_SYSTEM_PROMPT_TEMPLATE = """\
You write short educational TikTok-style scripts. Output strict JSON with three fields:
visual_hook, script, image_prompt.

SCRIPT CONSTRAINTS:
- 40-55 words (10-20 seconds spoken).
- Structure: Hook → Twist → Payoff.
- First sentence: curiosity gap, counterintuitive claim, or specific stakes. NEVER "Did you know" openers.
- One idea only. Concrete details: real names, dates, numbers.
- End with a reframe OR an open-loop question.
- Voice: smart friend at a bar, not lecturer. No "Imagine if…", no "Get this…", no "Buckle up".

VISUAL HOOK CONSTRAINTS:
- 3 to 7 words MAX (must fit one line on a mobile screen at large font size).
- Must NOT repeat the spoken hook verbatim — it must add a separate beat.
- Pick ONE of these moves:
  (a) state the surprising CONCLUSION of the script as a teaser
  (b) pose a sharp QUESTION the script answers
  (c) present a NUMBER or stat that demands explanation
  (d) make a CONTRADICTION with what viewers expect
- Sentence case overall; use ALL CAPS only on a 1-2 word emphasis if helpful.
- No emojis. No quotation marks. No trailing punctuation unless it's a question mark.

IMAGE PROMPT CONSTRAINTS (drives an AI image renderer):
- Pure VISUAL METAPHOR — describe shapes, silhouettes, objects, color, composition.
- ABSOLUTELY NO text, letters, numbers, equations, dates, names, labels, captions, "abstract symbols",
  "mathematical notation", hieroglyphs, or runes — diffusion models render all of those as garbled
  glyph soup. If you want to evoke "math" use lattices/spirals/polygons; "history" use era-appropriate
  silhouetted objects (tulip, ship, quill) WITHOUT plaques.
- DO NOT include humans, faces, or hands.
- 3 to 6 short phrases. Example: "A single tulip on a brass scale, outweighing a heap of gold coins, warm earthy tones, centered composition."
- Do NOT include style words like 'cinematic', 'photorealistic', '8k' — a style preamble is prepended for you.

{hook_type_block}
"""


SYSTEM_PROMPT = _SYSTEM_PROMPT_TEMPLATE.format(hook_type_block=render_hook_type_block())


def user_prompt(
    category: str,
    topic: str,
    hook_type: str,
    angle: str | None = None,
) -> str:
    parts = [
        f"Generate a {topic} short for a TikTok-style educational app.",
        "",
        f"SUBTOPIC: {category}",
        f"HOOK TYPE: {hook_type}",
    ]
    if angle:
        parts += ["", f"ANGLE / STEER: {angle}"]
    return "\n".join(parts)


# Belt-and-suspenders style enforcement — prepended on the fal.ai side
# even if the LLM-authored image_prompt drifts into stylistic territory.
IMAGE_STYLE_PREFIX = (
    "Bold editorial illustration, flat geometric vector style, strong silhouettes, "
    "high contrast, limited palette of 2-3 colors, centered composition, "
    "absolutely no text, no letters, no numbers, no digits, no symbols, "
    "no labels, no equations, no writing of any kind, no glyphs, "
    "no humans, no faces, no hands, no decorative ornament. "
    "Pure visual metaphor only. Portrait 3:4. Subject: "
)
